# cors
allow_cors_origins = ["localhost"]

# message
message_from_email = "Here's the sender name <here_is_the_address@here_is_the_domain>"
message_to_email = "Here's the reveiver name <here_is_the_address@here_is_the_domain>"

# retry
retry_count = 3
retry_timeout = 50

# smpt
smtp_connection_timeout = 10000